# Generated by Django 3.0 on 2021-12-19 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20211219_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_number', models.CharField(blank=True, max_length=220, null=True, verbose_name='Идентификационный номер')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='webapp.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_number', models.CharField(blank=True, max_length=220, null=True, verbose_name='Идентификационный номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Сокращенное название')),
                ('inn', models.CharField(blank=True, max_length=220, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=220, null=True, verbose_name='КПП')),
                ('departments', models.ManyToManyField(related_name='legalentities', to='webapp.Department', verbose_name='Департаменты')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в департамент')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Department', verbose_name='Департамент')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='departments',
            field=models.ManyToManyField(related_name='clients', through='webapp.ClientInDep', to='webapp.Department', verbose_name='Департаменты'),
        ),
    ]
